language: node_js
node_js:
  - "6.8"
  - "7.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8

cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test
