---
swagger: "2.0"
info:
  description: "This is a detailed ChapiVentas"
  version: "1.0.0"
  title: "ChapiVentas API"
basePath: "/api"
schemes:
- "https"
consumes:
  - application/json
paths:
  /carrera:
    post:
      tags:
      - "Carrera"
      summary: "Crear carrera"
      description: "Crear carrera"
      operationId: "postCarrera"
      parameters:
      - name: "Carrera"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/Carrera"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
      - "Carrera"
      summary: "Obtener carreras"
      description: "Obtener todas las carreras."
      operationId: "listUsersGET"
      responses:
        200:
          description: "Carreras"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Carrera"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /carrera/fecha:
    get:
      tags:
      - "Carrera Fechas"
      summary: "Obtener todas las fechas de una carrera"
      description: "Retorna todas las fechas importantes para una carrera"
      operationId: "getCarreraFecha"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "Carrera Fechas"
      summary: "Crear una fecha para carrera"
      description: "Creaci贸n de un registro en donde se almacene una fecha para una carrera"
      operationId: "postCarreraFechaMes"
      parameters:
      - name: "Mes"
        in: "body"
        description: "Mes"
        required: true
        example:
          ex:
            fecha: '2017-08-11'
            titulo: 'Parcial Calculo'
            descripcion: 'Ing. Aristondo'
        schema:
          $ref: "#/definitions/CarreraFechaMes"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /carrera/fecha/mes:
    post:
      tags:
      - "Carrera Fechas"
      summary: "Crear una fecha para carrera"
      description: "Creaci贸n de un registro en donde se almacene una fecha para una carrera"
      operationId: "postCarreraFecha"
      parameters:
      - name: "Carrera Fecha"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/CarreraFecha"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /promocion:
    post:
      tags:
      - "Promocion"
      summary: "Crear Promocion"
      description: "Crear promocion con fecha inicial y final"
      operationId: "postPromocion"
      parameters:
      - name: "Promocion"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/Promocion"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
      - "Promocion"
      summary: "Obtener todas las promociones"
      description: "Obtener todas las promociones"
      operationId: "listUsersGET"
      responses:
        200:
          description: "Promocion"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Promocion"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /promocion/delete:
    post:
      tags:
      - "Promocion"
      summary: "Eliminar una promoci贸n"
      description: "Eliminar una promoci贸n por ID"
      operationId: "deletePromocion"
      parameters:
      - name: "PromocionDelete"
        in: "body"
        description: "Id Promocion"
        required: true
        schema:
          $ref: "#/definitions/PromocionID"
      responses:
        200:
          description: "Promocion"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Promocion"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /promocion/query:
    get:
      tags:
      - "Promocion"
      summary: "Obtener todas las promociones entre fechas"
      description: "Obtener todas las promociones  dentro el rango especificado"
      operationId: "listUsersGET"
      parameters:
      - name: 'fechaInicio'
        in: 'query'
        description: 'Fecha inicial Promo'
        required: true
        example: '2017-08-02'
        type: 'string'
      - name: 'fechaFinal'
        in: 'query'
        description: 'Fecha Final Promo'
        required: true
        example: '2017-08-02'
        type: string
      responses:
        200:
          description: "Promocion"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Promocion"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /ventas:
    post:
      tags:
      - "Ventas"
      summary: "Crear Venta"
      description: "Crear Venta en una fecha"
      operationId: "postVenta"
      parameters:
      - name: "Venta"
        in: "body"
        description: "Venta object"
        required: true
        schema:
          $ref: "#/definitions/VentaPost"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
      - "Ventas"
      summary: "Obtener todas las ventas"
      description: "Obtener todas las Ventas"
      operationId: "listVentas"
      responses:
        200:
          description: "Ventas"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VentaList"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Promocion:
    type: object
    properties:
      tipo:
        type: string
      descuento:
        type: number
      descripcion:
        type: string
      fechaInicioPromo:
        type: string
      fechaFinalPromo:
        type: string
      color:
        type: string
  Carrera:
    type: object
    properties:
      nombre:
        type: string
      descripcion:
        type: string
      estudiantes:
        type: integer
  CarreraFecha:
    type: object
    properties:
      carrera_id:
        type: string
      fecha:
        type: string
  CarreraFechaMes:
    type: object
    properties:
      fecha:
        type: string
      titulo:
        type: string
      descripcion:
        type: string
  PromocionID:
    type: object
    properties:
      id:
        type: string
  VentaPost:
    type: object
    properties:
      date:
        type: string
      product:
        type: object
        properties:
          product_name:
            type: string
          product_price:
            type: number
      invoice:
        type: object
        properties:
          amount:
            type: number
          invoice_identifier:
            type: number
      quantity:
        type: number
  VentaList:
    type: object
    properties:
      fecha:
        type: object
        properties:
          fechaEvento:
            type: string
      producto:
        type: object
        properties:
          nombreProducto:
            type: object
            properties:
              nombre:
                type: string
          valorMonetario:
            type: object
            properties:
              moneda:
                type: string
              precio:
                type: number
      totalVenta:
        type: object
        properties:
          moneda:
            type: string
          precio:
            type: number
      cantidad:
        type: number

  Error:
    type: "object"
    properties:
      code:
        type: "integer"
      index:
        type: integer
      errmsg:
        type: "string"
      op:
        type: "array"
        items:
          type: "string"
